services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Mittwald\Varnishcache\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Mittwald\Varnishcache\Frontend\ContentObject\ContentObjectArrayInternalContentObject:
    tags:
      - name: frontend.contentobject
        identifier: 'COA_INT'

  Mittwald\Varnishcache\Service\EsiTagService:
    public: true

  Mittwald\Varnishcache\Service\VarnishCacheService:
    public: true
